/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TournamentCategoryListItemI, } from "./components/neo-tournament-category-list-view/tournament-category-list.model";
import { TournamentCategoryList, } from "./components/neo-tournament-category-list-item-view/tournament-category-list-item.model";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NeoTournamentCategoryListItemView {
        "data": TournamentCategoryListItemI;
    }
    interface NeoTournamentCategoryListView {
        "data": TournamentCategoryList;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNeoTournamentCategoryListItemViewElement extends Components.NeoTournamentCategoryListItemView, HTMLStencilElement {
    }
    var HTMLNeoTournamentCategoryListItemViewElement: {
        prototype: HTMLNeoTournamentCategoryListItemViewElement;
        new (): HTMLNeoTournamentCategoryListItemViewElement;
    };
    interface HTMLNeoTournamentCategoryListViewElement extends Components.NeoTournamentCategoryListView, HTMLStencilElement {
    }
    var HTMLNeoTournamentCategoryListViewElement: {
        prototype: HTMLNeoTournamentCategoryListViewElement;
        new (): HTMLNeoTournamentCategoryListViewElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "neo-tournament-category-list-item-view": HTMLNeoTournamentCategoryListItemViewElement;
        "neo-tournament-category-list-view": HTMLNeoTournamentCategoryListViewElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NeoTournamentCategoryListItemView {
        "data"?: TournamentCategoryListItemI;
    }
    interface NeoTournamentCategoryListView {
        "data"?: TournamentCategoryList;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "neo-tournament-category-list-item-view": NeoTournamentCategoryListItemView;
        "neo-tournament-category-list-view": NeoTournamentCategoryListView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "neo-tournament-category-list-item-view": LocalJSX.NeoTournamentCategoryListItemView & JSXBase.HTMLAttributes<HTMLNeoTournamentCategoryListItemViewElement>;
            "neo-tournament-category-list-view": LocalJSX.NeoTournamentCategoryListView & JSXBase.HTMLAttributes<HTMLNeoTournamentCategoryListViewElement>;
        }
    }
}
